version: '3.8'
services:

#  ONLY WORKS IN PROD
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

#  ONLY WORKS IN PROD
  pix_client:
    restart: unless-stopped
    build:
      context: ./combined_client
      dockerfile: local.Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pix_api
      - prosimos_api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  pix_api:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pix
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  rabbit:
    hostname: rabbit
    restart: unless-stopped
    image: rabbitmq:3-management
    container_name: prosimos-rabbitmq
    ports:
      - 5672:5672 # port for the worker for tasks management
      - 15672:15672 # GUI port

# Prosimos api seems to not process the simulation tasks when run in dev mode.
  prosimos_api:
    image: irynahalenok/prosimos-api:v1.3.0
    container_name: prosimos-api
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./src/celery/data:/app/src/celery/data
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
      - FLASK_DEBUG=1
    depends_on:
      - redis
      - rabbit

  redis:
    restart: unless-stopped
    image: redis:6-alpine
    ports:
      - 6379:6379


volumes:
  db:
    driver: local