version: '3.8'
services:
  pix_client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - '5173:80'
    depends_on:
      - pix_api

  pix_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db

  prosimos_api:
    build:
      context: ./prosimos-microservice
      dockerfile: Dockerfile.api
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pix
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./local.conf:/etc/nginx/nginx.conf
    depends_on:
      - pix_client
      - prosimos_client
      - prosimos_api
      - pix_api

volumes:
  db:
    driver: local