version: '3.8'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pix
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - api

volumes:
  db:
    driver: local