openapi: 3.1.0
info:
  title: PIX Project Management API Document
  version: 0.0.1
  description: |
    This API contains all endpoints related to creating a project in the PIX ecosystem.
    CRUD operations for project management.
paths:
  # GLOBAL PROJECT OPERATIONS
  /projects:
    get:
      summary: Get all projects
      description: Retrieve all projects accessible by the user
      operationId: get-all-projects
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
    post:
      summary: Create a new project
      operationId: create-project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
  # SPECIFIC PROJECT OPERATIONS
  /projects/{project_id}:
    get:
      summary: Get project information
      description: Retrieve the information of a specific project.
      operationId: get-project
      parameters:
        - $ref: "#/components/parameters/project_id"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"

    put:
      summary: Update project information
      operationId: update-project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/projectInformation"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"


components:
  parameters:
    project_id:
      description: UUID of a project
      name: project_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/identifier"

  schemas:
    tag:
      type: string
    identifier:
      type: string
    status:
      type: string
#      EXPAND THIS
    tags:
      type: array
      minItems: 0
      maxItems: 100
      items:
        $ref: "#/components/schemas/tag"

    projectInformation:
      type: object
      properties:
        name:
          type: string
        tags:
          $ref: "#/components/schemas/tags"