services:
  projects:
    build:
      context: .
    ports:
      - 8030:8000
    env_file:
      - .env
    depends_on:
      projects-db:
        condition: service_healthy
    networks:
      - backend
  projects-db:
    image: postgres
    restart: on-failure
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5435:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
    name: pix_backend
