services:
  files:
    build:
      context: .
    ports:
      - 8010:8000
    env_file:
      - .env
    depends_on:
      files-db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - uploads:/var/tmp/uploads:rw
  files-db:
    image: postgres
    restart: on-failure
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
volumes:
  db-data:
  uploads:
networks:
  backend:
    name: pix_backend
