receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:
processors:
  batch:
exporters:
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging,zipkin ]