- name: Build & Deploy
  hosts:
    - pix-w1
  remote_user: ubuntu
  become: true
  vars:
    base_dir_remote: /srv/pix-portal
    secrets_dir: ./secrets

  tasks:
    - name: Copy Caddyfile
      ansible.builtin.copy:
        src: "{{ secrets_dir }}/Caddyfile"
        dest: "{{ base_dir_remote }}/"
        mode: 0644

    - name: Copy Docker Compose configuration
      ansible.builtin.copy:
        src: "{{ secrets_dir }}/compose.yaml"
        dest: "{{ base_dir_remote }}/"
        mode: 0644

    - name: Copy secrets
      ansible.builtin.copy:
        src: "{{ secrets_dir }}"
        dest: "{{ base_dir_remote }}/"
        mode: 0644

    - name: Create mount directories
      ansible.builtin.file:
        path: "/mnt/data/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - pix-portal
        - pix-portal/postgres-data
        - pix-portal/postgres-data/pix
        - pix-portal/uploads
        - pix-portal/kafka
        - pix-portal/caddy
        - pix-portal/caddy/data
        - pix-portal/caddy/config
        - pix-portal/simod
        - pix-portal/prosimos
        - pix-portal/kronos
        - pix-portal/kronos-db
        - pix-portal/optimos

    - name: Start Docker Compose
      ansible.builtin.command: docker compose -f "{{ base_dir_remote }}/compose.yaml" up -d --build --remove-orphans
      args:
        chdir: "{{ base_dir_remote }}"
