name: Docker Image CI - PROD deployment image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./combined_client --file combined_client/Dockerfile --tag pix-client-production:$(date +%s)
